Potentially better landing page
fosscord/fosscord-landingpage pull request #57
Opened 2022-09-01 10:37 UTC by MaddyUnderStars

Replaces the old sections with a features list, with ( imo ) clearer wording and markings.
Some of the wording may not be the best, feel free to correct

2022-09-01 10:54 UTC, MaddyUnderStars commented
![localhost_3000_](https://user-images.githubusercontent.com/46743919/187897638-df9cae37-7366-4e75-824d-82af9b2d7f41.png)
screenshot for the lazy

2022-09-02 02:13 UTC, MaddyUnderStars commented
![localhost_3000_](https://user-images.githubusercontent.com/46743919/188044134-d6e9f2d1-1063-4c0c-a9cb-07877f28ffd5.png)
moved links

2022-09-02 02:13 UTC, MaddyUnderStars commented
oh the screenshot broke. you get the point, though

2022-09-12 09:26 UTC, TheArcaneBrony approved these changes
looks fine to me

2022-09-30 14:39 UTC, MaddyUnderStars commented
@erkinalp thoughts? I don't have rights to merge on this repo.

2022-09-30 15:50 UTC, erkinalp commented on components/features.vue
> +					<p>This is by <i>no</i> means a complete list of features, planned or completed, that the team
```suggestion
					<p>This is <i>by no means</i> a complete list of features, planned or completed, that the team
```

2022-09-30 15:50 UTC, erkinalp commented on components/features.vue
> +						each component.
users might ask why it is a monorepo when components may be run separately, needs explanation

2022-10-26 08:26 UTC, TheArcaneBrony commented on components/features.vue
> +					<p>This is by <i>no</i> means a complete list of features, planned or completed, that the team
I agree with this change, while a small change, I feel like it would improve UX a little

2022-10-27 04:46 UTC, TheArcaneBrony approved these changes

2022-10-27 20:01 UTC, FSG-Cat approved these changes

2022-10-27 20:13 UTC, erkinalp reviewed
reasoning for monorepo structure not explained clearly

2022-11-09 13:56 UTC, erkinalp approved these changes

2022-11-10 01:02 UTC, MaddyUnderStars commented
@CanadaHonk Hey, sorry for the ping, but would you mind checking out what you think of the above as well? I would appreciate any feedback you have

2022-11-10 08:24 UTC, erkinalp requested changes
Hey, looks good to me, except that reasoning for the monorepo is still missing

2022-11-10 08:26 UTC, MaddyUnderStars commented
> Hey, looks good to me, except that reasoning for the monorepo is still missing

Yeah I removed that section because its not really a feature to be advertised. Do you think that reasoning should still be there? Would you fit it in as another feature ( which I'd rather not do as it'd break the 3x3 grid we have going on ) or replace an existing one? Personally I think an explanation for why its a mono repo would be better fit for the documentation

2022-11-10 08:29 UTC, erkinalp commented
@MaddyUnderStars OK, in docs FAQ then.

2022-11-10 08:29 UTC, erkinalp approved these changes

2022-11-17 08:06 UTC, MaddyUnderStars commented
@erkinalp @TheArcaneBrony If we're happen with this, can someone merge for me? I don't have write perms here

2022-11-17 16:12 UTC, erkinalp commented
@MaddyUnderStars neither do i

2022-11-17 19:41 UTC, merged